# Generated by Django 4.2.6 on 2024-06-17 13:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_taskmodel_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substasks', to='api.taskmodel')),
            ],
        ),
    ]
