# Generated by Django 4.2.6 on 2024-06-20 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_subtaskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtaskmodel',
            name='assigned_to',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='subtaskmodel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='api.taskmodel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
