# Generated by Django 4.2.6 on 2024-06-20 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subtaskmodel_assigned_to_alter_subtaskmodel_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='api.taskmodel')),
            ],
        ),
    ]
